### ISSUE TITLE
Package Name refact

### ISSUE THREAD

**Issue by Jacksunwei** [vitavva/genfengxue#2]
make the package name is the same as company domain, say com.genfengxue

**Comment by lutaoact** [comment]
I have checked the package name, and we use 'com.genfengxue.windenglish', I suggest using 'com.genfengxue' instead. we can remove the suffix 'windenglish', for it's meaningless and the package name is too long.

**Comment by Jacksunwei** [comment]
not really, com.genfengxue is the company name, windenglish is the product name. @lutaoact
