### ISSUE TITLE
关于二级菜单的一些说明

### ISSUE THREAD

**Issue by lutaoact** [vitavva/genfengxue#23]
1 第一级菜单是course列表，但courseNo可能不是连续的，可能是1，2，3，50这种。因为50之前的一些课程还没有开发完，这些课程未来会穿插进去。现在的api返回的数据排序是按照courseNo升序排的，但排序方式之后可能调整。你在设计的时候不要依赖现在的顺序。

2 直捷英语，也就是course 2，lesson是连续的，从1开始编号，现在有1-100课了。但其它的course不一定是这样的。刚刚新增的新概念，也就是course 1的，课程只有单数课，而且从71开始，所以lessonNo是71，73，75……不知道这个东西对你的设计会不会有影响？

都跟你提前说一下，你在设计的时候可以考虑进去。
@Jacksunwei 
@lius0035

**Comment by Jacksunwei** [comment]
现在的问题是Course的页面没有，需要涉及定稿。
我觉得页面布局可以沿用Lesson的layout，但是现在问题是都不能点进去。所以可能只有一个课程是可以点的，需要这么快做嘛？
如果做得话，可能在user profile要加些能选什么课的信息

**Comment by lutaoact** [comment]
这是course的页面，跟lesson比较像，但是不需要那个编号了。

![clipboard image](https://cloud.githubusercontent.com/assets/2290247/7159716/b89cbe5c-e3b6-11e4-9b70-bec929b70c60.png)
还有，现在course里面拿到的数据是测试数据，等你开发完成后，涛哥会把多余的删掉，只留course1和course2，现在course2中已经有lesson了，course1的数据，涛哥今晚就会导进去，之后相应的lesson列表也就有了。
