### ISSUE TITLE
用户登录后，如果没有email，强制填写email和nickname

### ISSUE THREAD

**Issue by lutaoact** [vitavva/genfengxue#24]
用户首次登录，拿到profile，如果没有email，则强制跳转到一个页面，要求填入nickname和email。

服务器端会检查nickname的唯一性和email的格式。
nickname唯一是因为之后还会有一个排行榜功能，nickname如果重复，会在排行榜上造成迷惑，而且我们的用户数也比较小，所以唯一不会造成太大问题。

有任何问题，随时交流。
@Jacksunwei

**Comment by Jacksunwei** [comment]
这个有多急？放在milestone2如何？ @lutaoact

**Comment by lutaoact** [comment]
对答案的界面里，点带下划线的单词，会出现一个对话框，然后点那个头像，会到提问界面，现在的提问是通过邮件发过来的，而回答也是通过邮件发回去，如果没有email，我们没法给学生回复。
这个提问本来是应该直接发给服务器端，但老师回答完之后，我们的app还没有展示相应结果的界面。而这个功能可能需要的时间还比较长，所以需要他们填个邮箱，然后舜哥会把回答通过邮件发给学生。
这个方案感觉不太好，你有没有什么更好的方案？这个界面涛哥也可以写，就是要麻烦你整合进去，你看怎么样？

**Comment by Jacksunwei** [comment]
我觉得可以，如果你真的写好了的话，整合是没有工作量的。。。只是填几行startActivity
@lutaoact
