### ISSUE TITLE
允许离线对答案

### ISSUE THREAD

**Issue by lutaoact** [vitavva/genfengxue#25]
用户对答案，也就是Check页面，需要到网上去拿文本资料
希望达到的效果是：可以离线对答案。我觉得可以在下载视频的时候，把文本资料也在本地存一份，如果之后对答案的时候，无法联网，就用本地的资料。
你看怎么样？

@Jacksunwei

**Comment by Jacksunwei** [comment]
可以，就是附带一次api请求，就会自动cache在本地，但是我还没有看过Check页面，如果要加新功能，无法估算工作量 @lutaoact

**Comment by Jacksunwei** [comment]
但是我还没有看过Check页面，如果要加新功能，无法估算工作量

**Comment by lutaoact** [comment]
Check界面，有很多注释掉的代码都不用了。如果这个页面重构不了，我们就先用他的。就在他发网络请求那个地方，我们加一个去读文件，简单点应该不会很花时间。
有什么问题，随时说，我有空的话也去看代码。
@Jacksunwei
