### ISSUE TITLE
安卓官方设计指南

### ISSUE THREAD

**Issue by lius0035** [vitavva/genfengxue#28]
这个是你说的安卓官方指南吗, 我之后best practice看看  @Jacksunwei 

https://developer.android.com/design/index.html

**Comment by Jacksunwei** [comment]
差不多，不过我上次跟你说的返回键那个是在开发者大会上那个Google的人特意说的，我不确定这个里面哪里会说。
这个里面我感觉已经大部分篇幅将material design了，比较偏设计，你酌情吧，不一定在这上面耽误很多时间 @lius0035
