### ISSUE TITLE
选课之后怎么重新选课？

### ISSUE THREAD

**Issue by Jacksunwei** [vitavva/genfengxue#31]
怎么重新选课？添加个按钮？
@lutaoact @lius0035

**Comment by lius0035** [comment]
你是指进入了二级菜单之后怎么退回到一级菜单对吗?

我目前还没有一个很好的方案. 之前我的方案是如图
![image](https://cloud.githubusercontent.com/assets/11885354/7214807/6eaca82c-e5ee-11e4-9614-98a1e83c3b2f.png)

你有什么别的想法吗? @Jacksunwei

**Comment by Jacksunwei** [comment]
先就做了一个滑动退出，功能实现了
@lius0035
