### ISSUE TITLE
视频播放过程的一些问题

### ISSUE THREAD

**Issue by lutaoact** [vitavva/genfengxue#33]
按下home键退出，再重新进来之后，能否从退出时的位置继续播放。
如果不行的话，那就恢复到开始播放之前的界面，就是显示“开始”按钮的那个界面。

按下back键，我们会弹出一个对话框，这个时候，可不可以把视频暂停了，如果是在录音界面，就把录音也暂停了，对话框消失之后继续。

@Jacksunwei 
@lius0035

**Comment by Jacksunwei** [comment]
视频可以暂停，录音不能暂停，而且我考虑反正你还能倒退，所以不暂停应该会比较正常。
@lius0035  @lutaoact
